channel_sources:
  - freecad/label/qt6, conda-forge
channel_targets:
  - freecad qt6
c_stdlib_version:          # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.12"                # [osx and x86_64]
vtk:
  - 9.3.0